function registerLegacyBindings() {
    Game.ui.bindElement('scienceps', function(){ return Game.settings.format(scienceps, 1); });
    Game.ui.bindElement('uraniumps', function(){ return Game.settings.format(uraniumps); });
    Game.ui.bindElement('oilps', function(){ return Game.settings.format(oilps); });
    Game.ui.bindElement('metalps', function(){ return Game.settings.format(metalps); });
    Game.ui.bindElement('gemps', function(){ return Game.settings.format(gemps); });
    Game.ui.bindElement('charcoalps', function(){ return Game.settings.format(charcoalps); });

    Game.ui.bindElement('woodps', function(){ return Game.settings.format(woodps); });
    Game.ui.bindElement('lunariteps', function(){ return Game.settings.format(lunariteps); });
    Game.ui.bindElement('methaneps', function(){ return Game.settings.format(methaneps); });
    Game.ui.bindElement('titaniumps', function(){ return Game.settings.format(titaniumps); });
    Game.ui.bindElement('goldps', function(){ return Game.settings.format(goldps); });
    Game.ui.bindElement('silverps', function(){ return Game.settings.format(silverps); });
    Game.ui.bindElement('siliconps', function(){ return Game.settings.format(siliconps); });
    Game.ui.bindElement('lavaps', function(){ return Game.settings.format(lavaps); });
    Game.ui.bindElement('hydrogenps', function(){ return Game.settings.format(hydrogenps); });
    Game.ui.bindElement('heliumps', function(){ return Game.settings.format(heliumps); });
    Game.ui.bindElement('iceps', function(){ return Game.settings.format(iceps); });
    Game.ui.bindElement('plasmaps', function(){ return Game.settings.format(plasmaps); });
    Game.ui.bindElement('meteoriteps', function(){ return Game.settings.format(meteoriteps); });
    Game.ui.bindElement('rocketFuelps', function(){ return Game.settings.format(rocketFuelps, 1); });
    Game.ui.bindElement('antimatterps', function(){ return Game.settings.format(antimatterps, 1); });

    Game.ui.bindElement('energyps', function(){
        if(energyps >= 0){
            if(energyps > 250){
                return Game.settings.format(energyps);
            }
            else{
                return Game.settings.format(energyps*2)/2;
            }
        }
        else{
            if(energyps < -250){
                return Math.round(energyps);
            }
            else{
                return Math.round(energyps*2)/2;
            }
        }
    });

    Game.ui.bindElement('energy', function(){ return Game.settings.format(energy); });
    Game.ui.bindElement('plasma', function(){ return Game.settings.format(plasma); });
    Game.ui.bindElement('oil', function(){ return Game.settings.format(oil); });
    Game.ui.bindElement('metal', function(){ return Game.settings.format(metal); });
    Game.ui.bindElement('gem', function(){ return Game.settings.format(gem); });
    Game.ui.bindElement('charcoal', function(){ return Game.settings.format(charcoal); });
    Game.ui.bindElement('wood', function(){ return Game.settings.format(wood); });
    Game.ui.bindElement('lunarite', function(){ return Game.settings.format(lunarite); });
    Game.ui.bindElement('methane', function(){ return Game.settings.format(methane); });
    Game.ui.bindElement('titanium', function(){ return Game.settings.format(titanium); });
    Game.ui.bindElement('gold', function(){ return Game.settings.format(gold); });
    Game.ui.bindElement('silver', function(){ return Game.settings.format(silver); });
    Game.ui.bindElement('silicon', function(){ return Game.settings.format(silicon); });
    Game.ui.bindElement('uranium', function(){ return Game.settings.format(uranium); });
    Game.ui.bindElement('lava', function(){ return Game.settings.format(lava); });
    Game.ui.bindElement('hydrogen', function(){ return Game.settings.format(hydrogen); });
    Game.ui.bindElement('helium', function(){ return Game.settings.format(helium); });
    Game.ui.bindElement('ice', function(){ return Game.settings.format(ice); });
    Game.ui.bindElement('meteorite', function(){ return Game.settings.format(meteorite); });

    Game.ui.bindElement('plasmaStorage', function(){ return Game.settings.format(getMaxPlasma()); });
    Game.ui.bindElement('energyStorage', function(){ return Game.settings.format(getMaxEnergy()); });
    Game.ui.bindElement('uraniumStorage', function(){ return Game.settings.format(uraniumStorage); });
    Game.ui.bindElement('uraniumNextStorage', function(){ return Game.settings.format(uraniumNextStorage); });
    Game.ui.bindElement('uraniumStorageCost', function(){ return Game.settings.format(uraniumStorage); });
    Game.ui.bindElement('uraniumStorageLunariteCost', function(){ return Game.settings.format(uraniumStorage/2.5); });
    Game.ui.bindElement('oilStorage', function(){ return Game.settings.format(oilStorage); });
    Game.ui.bindElement('oilNextStorage', function(){ return Game.settings.format(oilNextStorage); });
    Game.ui.bindElement('oilStorageCost', function(){ return Game.settings.format(oilStorage); });
    Game.ui.bindElement('oilStorageMetalCost', function(){ return Game.settings.format(oilStorage/2.5); });
    Game.ui.bindElement('metalStorage', function(){ return Game.settings.format(metalStorage); });
    Game.ui.bindElement('metalNextStorage', function(){ return Game.settings.format(metalNextStorage); });
    Game.ui.bindElement('metalStorageCost', function(){ return Game.settings.format(metalStorage); });
    Game.ui.bindElement('gemStorage', function(){ return Game.settings.format(gemStorage); });
    Game.ui.bindElement('gemNextStorage', function(){ return Game.settings.format(gemNextStorage); });
    Game.ui.bindElement('gemStorageCost', function(){ return Game.settings.format(gemStorage); });
    Game.ui.bindElement('gemStorageMetalCost', function(){ return Game.settings.format(gemStorage/2.5); });
    Game.ui.bindElement('charcoalStorage', function(){ return Game.settings.format(charcoalStorage); });
    Game.ui.bindElement('charcoalNextStorage', function(){ return Game.settings.format(charcoalNextStorage); });
    Game.ui.bindElement('charcoalStorageCost', function(){ return Game.settings.format(charcoalStorage); });
    Game.ui.bindElement('charcoalStorageMetalCost', function(){ return Game.settings.format(charcoalStorage/2.5); });
    Game.ui.bindElement('woodStorage', function(){ return Game.settings.format(woodStorage); });
    Game.ui.bindElement('woodNextStorage', function(){ return Game.settings.format(woodNextStorage); });
    Game.ui.bindElement('woodStorageCost', function(){ return Game.settings.format(woodStorage); });
    Game.ui.bindElement('woodStorageMetalCost', function(){ return Game.settings.format(woodStorage/2.5); });
    Game.ui.bindElement('lunariteStorage', function(){ return Game.settings.format(lunariteStorage); });
    Game.ui.bindElement('lunariteNextStorage', function(){ return Game.settings.format(lunariteNextStorage); });
    Game.ui.bindElement('lunariteStorageCost', function(){ return Game.settings.format(lunariteStorage); });
    Game.ui.bindElement('lunariteStorageMetalCost', function(){ return Game.settings.format(lunariteStorage*4); });
    Game.ui.bindElement('methaneStorage', function(){ return Game.settings.format(methaneStorage); });
    Game.ui.bindElement('methaneNextStorage', function(){ return Game.settings.format(methaneNextStorage); });
    Game.ui.bindElement('methaneStorageCost', function(){ return Game.settings.format(methaneStorage); });
    Game.ui.bindElement('methaneStorageLunariteCost', function(){ return Game.settings.format(methaneStorage/2.5); });
    Game.ui.bindElement('titaniumStorage', function(){ return Game.settings.format(titaniumStorage); });
    Game.ui.bindElement('titaniumNextStorage', function(){ return Game.settings.format(titaniumNextStorage); });
    Game.ui.bindElement('titaniumStorageCost', function(){ return Game.settings.format(titaniumStorage); });
    Game.ui.bindElement('titaniumStorageLunariteCost', function(){ return Game.settings.format(titaniumStorage/2.5); });
    Game.ui.bindElement('goldStorage', function(){ return Game.settings.format(goldStorage); });
    Game.ui.bindElement('goldNextStorage', function(){ return Game.settings.format(goldNextStorage); });
    Game.ui.bindElement('goldStorageCost', function(){ return Game.settings.format(goldStorage); });
    Game.ui.bindElement('goldStorageLunariteCost', function(){ return Game.settings.format(goldStorage/2.5); });
    Game.ui.bindElement('silverStorage', function(){ return Game.settings.format(silverStorage); });
    Game.ui.bindElement('silverNextStorage', function(){ return Game.settings.format(silverNextStorage); });
    Game.ui.bindElement('silverStorageCost', function(){ return Game.settings.format(silverStorage); });
    Game.ui.bindElement('silverStorageLunariteCost', function(){ return Game.settings.format(silverStorage/2.5); });
    Game.ui.bindElement('siliconStorage', function(){ return Game.settings.format(siliconStorage); });
    Game.ui.bindElement('siliconNextStorage', function(){ return Game.settings.format(siliconNextStorage); });
    Game.ui.bindElement('siliconStorageCost', function(){ return Game.settings.format(siliconStorage); });
    Game.ui.bindElement('siliconStorageLunariteCost', function(){ return Game.settings.format(siliconStorage/2.5); });
    Game.ui.bindElement('lavaStorage', function(){ return Game.settings.format(lavaStorage); });
    Game.ui.bindElement('lavaNextStorage', function(){ return Game.settings.format(lavaNextStorage); });
    Game.ui.bindElement('lavaStorageCost', function(){ return Game.settings.format(lavaStorage); });
    Game.ui.bindElement('lavaStorageLunariteCost', function(){ return Game.settings.format(lavaStorage/2.5); });
    Game.ui.bindElement('hydrogenStorage', function(){ return Game.settings.format(hydrogenStorage); });
    Game.ui.bindElement('hydrogenNextStorage', function(){ return Game.settings.format(hydrogenNextStorage); });
    Game.ui.bindElement('hydrogenStorageCost', function(){ return Game.settings.format(hydrogenStorage); });
    Game.ui.bindElement('hydrogenStorageLunariteCost', function(){ return Game.settings.format(hydrogenStorage/2.5); });
    Game.ui.bindElement('heliumStorage', function(){ return Game.settings.format(heliumStorage); });
    Game.ui.bindElement('heliumNextStorage', function(){ return Game.settings.format(heliumNextStorage); });
    Game.ui.bindElement('heliumStorageCost', function(){ return Game.settings.format(heliumStorage); });
    Game.ui.bindElement('heliumStorageLunariteCost', function(){ return Game.settings.format(heliumStorage/2.5); });
    Game.ui.bindElement('iceStorage', function(){ return Game.settings.format(iceStorage); });
    Game.ui.bindElement('iceNextStorage', function(){ return Game.settings.format(iceNextStorage); });
    Game.ui.bindElement('iceStorageCost', function(){ return Game.settings.format(iceStorage); });
    Game.ui.bindElement('iceStorageLunariteCost', function(){ return Game.settings.format(iceStorage/2.5); });
    Game.ui.bindElement('meteoriteStorage', function(){ return Game.settings.format(meteoriteStorage); });
    Game.ui.bindElement('meteoriteNextStorage', function(){ return Game.settings.format(meteoriteNextStorage); });
    Game.ui.bindElement('meteoriteStorageCost', function(){ return Game.settings.format(meteoriteStorage); });
    Game.ui.bindElement('meteoriteStorageLunariteCost', function(){ return Game.settings.format(meteoriteStorage*4); });
    Game.ui.bindElement('PSU', function(){ return Game.settings.format(PSU); });
    Game.ui.bindElement('PSUSilverCost', function(){ return Game.settings.format(PSUSilverCost); });
    Game.ui.bindElement('PSUGoldCost', function(){ return Game.settings.format(PSUGoldCost); });
    Game.ui.bindElement('PSUUraniumCost', function(){ return Game.settings.format(PSUUraniumCost); });
    Game.ui.bindElement('PSUT2', function(){ return Game.settings.format(PSUT2); });
    Game.ui.bindElement('PSUT2SilverCost', function(){ return Game.settings.format(PSUT2SilverCost); });
    Game.ui.bindElement('PSUT2GoldCost', function(){ return Game.settings.format(PSUT2GoldCost); });
    Game.ui.bindElement('PSUT2UraniumCost', function(){ return Game.settings.format(PSUT2UraniumCost); });
    Game.ui.bindElement('heater', function(){ return Game.settings.format(heater); });
    Game.ui.bindElement('heaterLunariteCost', function(){ return Game.settings.format(heaterLunariteCost); });
    Game.ui.bindElement('heaterGemCost', function(){ return Game.settings.format(heaterGemCost); });
    Game.ui.bindElement('heaterSiliconCost', function(){ return Game.settings.format(heaterSiliconCost); });
    Game.ui.bindElement('plasmatic', function(){ return Game.settings.format(plasmatic); });
    Game.ui.bindElement('plasmaticLunariteCost', function(){ return Game.settings.format(plasmaticLunariteCost); });
    Game.ui.bindElement('plasmaticSiliconCost', function(){ return Game.settings.format(plasmaticSiliconCost); });
    Game.ui.bindElement('plasmaticMeteoriteCost', function(){ return Game.settings.format(plasmaticMeteoriteCost); });
    Game.ui.bindElement('battery', function(){ return Game.settings.format(battery); });
    Game.ui.bindElement('batteryMetalCost', function(){ return Game.settings.format(batteryMetalCost); });
    Game.ui.bindElement('batteryGemCost', function(){ return Game.settings.format(batteryGemCost); });
    Game.ui.bindElement('batteryLunariteCost', function(){ return Game.settings.format(batteryLunariteCost); });
    Game.ui.bindElement('batteryT2', function(){ return Game.settings.format(batteryT2); });
    Game.ui.bindElement('batteryT2MetalCost', function(){ return Game.settings.format(batteryT2MetalCost); });
    Game.ui.bindElement('batteryT2GemCost', function(){ return Game.settings.format(batteryT2GemCost); });
    Game.ui.bindElement('batteryT2LunariteCost', function(){ return Game.settings.format(batteryT2LunariteCost); });
    Game.ui.bindElement('batteryT3', function(){ return Game.settings.format(batteryT3); });
    Game.ui.bindElement('batteryT3MetalCost', function(){ return Game.settings.format(batteryT3MetalCost); });
    Game.ui.bindElement('batteryT3GemCost', function(){ return Game.settings.format(batteryT3GemCost); });
    Game.ui.bindElement('batteryT3LunariteCost', function(){ return Game.settings.format(batteryT3LunariteCost); });
	Game.ui.bindElement('batteryT4', function(){ return Game.settings.format(batteryT4); });
    Game.ui.bindElement('batteryT4MetalCost', function(){ return Game.settings.format(batteryT4MetalCost); });
    Game.ui.bindElement('batteryT4GemCost', function(){ return Game.settings.format(batteryT4GemCost); });
    Game.ui.bindElement('batteryT4LunariteCost', function(){ return Game.settings.format(batteryT4LunariteCost); });
    Game.ui.bindElement('charcoalEngine', function(){ return Game.settings.format(charcoalEngine); });
    Game.ui.bindElement('charcoalEngineMetalCost', function(){ return Game.settings.format(charcoalEngineMetalCost); });
    Game.ui.bindElement('charcoalEngineGemCost', function(){ return Game.settings.format(charcoalEngineGemCost); });
    Game.ui.bindElement('charcoalEngineOutput', function(){ return Game.settings.format(charcoalEngineOutput); });
    Game.ui.bindElement('solarPanel', function(){ return Game.settings.format(solarPanel); });
    Game.ui.bindElement('solarPanelMetalCost', function(){ return Game.settings.format(solarPanelMetalCost); });
    Game.ui.bindElement('solarPanelGemCost', function(){ return Game.settings.format(solarPanelGemCost); });
    Game.ui.bindElement('solarPanelOutput', function(){ return solarPanelOutput; });
    Game.ui.bindElement('methaneStation', function(){ return Game.settings.format(methaneStation); });
    Game.ui.bindElement('methaneStationLunariteCost', function(){ return Game.settings.format(methaneStationLunariteCost); });
    Game.ui.bindElement('methaneStationTitaniumCost', function(){ return Game.settings.format(methaneStationTitaniumCost); });
    Game.ui.bindElement('nuclearStation', function(){ return Game.settings.format(nuclearStation); });
    Game.ui.bindElement('nuclearStationLunariteCost', function(){ return Game.settings.format(nuclearStationLunariteCost); });
    Game.ui.bindElement('nuclearStationTitaniumCost', function(){ return Game.settings.format(nuclearStationTitaniumCost); });
    Game.ui.bindElement('magmatic', function(){ return Game.settings.format(magmatic); });
    Game.ui.bindElement('magmaticLunariteCost', function(){ return Game.settings.format(magmaticLunariteCost); });
    Game.ui.bindElement('magmaticGemCost', function(){ return Game.settings.format(magmaticGemCost); });
    Game.ui.bindElement('magmaticSilverCost', function(){ return Game.settings.format(magmaticSilverCost); });
    Game.ui.bindElement('fusionReactor', function(){ return Game.settings.format(fusionReactor); });
    Game.ui.bindElement('fusionReactorLunariteCost', function(){ return Game.settings.format(fusionReactorLunariteCost); });
    Game.ui.bindElement('fusionReactorTitaniumCost', function(){ return Game.settings.format(fusionReactorTitaniumCost); });
    Game.ui.bindElement('fusionReactorSiliconCost', function(){ return Game.settings.format(fusionReactorSiliconCost); });
    Game.ui.bindElement('pump', function(){ return Game.settings.format(pump); });
    Game.ui.bindElement('pumpMetalCost', function(){ return Game.settings.format(pumpMetalCost); });
    Game.ui.bindElement('pumpGemCost', function(){ return Game.settings.format(pumpGemCost); });
    Game.ui.bindElement('pumpjack', function(){ return Game.settings.format(pumpjack); });
    Game.ui.bindElement('pumpjackOilCost', function(){ return Game.settings.format(pumpjackOilCost); });
    Game.ui.bindElement('pumpjackGemCost', function(){ return Game.settings.format(pumpjackGemCost); });
    Game.ui.bindElement('pumpjackMetalCost', function(){ return Game.settings.format(pumpjackMetalCost); });
    Game.ui.bindElement('pumpjackOutput', function(){ return Game.settings.format(pumpjackOutput); });
    Game.ui.bindElement('oilField', function(){ return Game.settings.format(oilField); });
    Game.ui.bindElement('oilFieldTitaniumCost', function(){ return Game.settings.format(oilFieldTitaniumCost); });
    Game.ui.bindElement('oilFieldLunariteCost', function(){ return Game.settings.format(oilFieldLunariteCost); });
    Game.ui.bindElement('oilFieldSiliconCost', function(){ return Game.settings.format(oilFieldSiliconCost); });
    Game.ui.bindElement('oilRig', function(){ return Game.settings.format(oilRig); });
    Game.ui.bindElement('oilRigTitaniumCost', function(){ return Game.settings.format(oilRigTitaniumCost); });
    Game.ui.bindElement('oilRigLunariteCost', function(){ return Game.settings.format(oilRigLunariteCost); });
    Game.ui.bindElement('oilRigMeteoriteCost', function(){ return Game.settings.format(oilRigMeteoriteCost); });
    Game.ui.bindElement('miner', function(){ return Game.settings.format(miner); });
    Game.ui.bindElement('minerMetalCost', function(){ return Game.settings.format(minerMetalCost); });
    Game.ui.bindElement('minerWoodCost', function(){ return Game.settings.format(minerWoodCost); });
    Game.ui.bindElement('heavyDrill', function(){ return Game.settings.format(heavyDrill); });
    Game.ui.bindElement('heavyDrillMetalCost', function(){ return Game.settings.format(heavyDrillMetalCost); });
    Game.ui.bindElement('heavyDrillGemCost', function(){ return Game.settings.format(heavyDrillGemCost); });
    Game.ui.bindElement('heavyDrillOilCost', function(){ return Game.settings.format(heavyDrillOilCost); });
    Game.ui.bindElement('heavyDrillOutput', function(){ return Game.settings.format(heavyDrillOutput); });
    Game.ui.bindElement('gigaDrill', function(){ return Game.settings.format(gigaDrill); });
    Game.ui.bindElement('gigaDrillLunariteCost', function(){ return Game.settings.format(gigaDrillLunariteCost); });
    Game.ui.bindElement('gigaDrillGemCost', function(){ return Game.settings.format(gigaDrillGemCost); });
    Game.ui.bindElement('gigaDrillSiliconCost', function(){ return Game.settings.format(gigaDrillSiliconCost); });
    Game.ui.bindElement('quantumDrill', function(){ return Game.settings.format(quantumDrill); });
    Game.ui.bindElement('quantumDrillLunariteCost', function(){ return Game.settings.format(quantumDrillLunariteCost); });
    Game.ui.bindElement('quantumDrillGoldCost', function(){ return Game.settings.format(quantumDrillGoldCost); });
    Game.ui.bindElement('quantumDrillMeteoriteCost', function(){ return Game.settings.format(quantumDrillMeteoriteCost); });
    Game.ui.bindElement('gemMiner', function(){ return Game.settings.format(gemMiner); });
    Game.ui.bindElement('gemMinerMetalCost', function(){ return Game.settings.format(gemMinerMetalCost); });
    Game.ui.bindElement('gemMinerGemCost', function(){ return Game.settings.format(gemMinerGemCost); });
    Game.ui.bindElement('advancedDrill', function(){ return Game.settings.format(advancedDrill); });
    Game.ui.bindElement('advancedDrillMetalCost', function(){ return Game.settings.format(advancedDrillMetalCost); });
    Game.ui.bindElement('advancedDrillGemCost', function(){ return Game.settings.format(advancedDrillGemCost); });
    Game.ui.bindElement('advancedDrillOilCost', function(){ return Game.settings.format(advancedDrillOilCost); });
    Game.ui.bindElement('advancedDrillOutput', function(){ return Game.settings.format(advancedDrillOutput); });
    Game.ui.bindElement('diamondDrill', function(){ return Game.settings.format(diamondDrill); });
    Game.ui.bindElement('diamondDrillLunariteCost', function(){ return Game.settings.format(diamondDrillLunariteCost); });
    Game.ui.bindElement('diamondDrillGemCost', function(){ return Game.settings.format(diamondDrillGemCost); });
    Game.ui.bindElement('diamondDrillSiliconCost', function(){ return Game.settings.format(diamondDrillSiliconCost); });
    Game.ui.bindElement('carbyneDrill', function(){ return Game.settings.format(carbyneDrill); });
    Game.ui.bindElement('carbyneDrillLunariteCost', function(){ return Game.settings.format(carbyneDrillLunariteCost); });
    Game.ui.bindElement('carbyneDrillGemCost', function(){ return Game.settings.format(carbyneDrillGemCost); });
    Game.ui.bindElement('carbyneDrillMeteoriteCost', function(){ return Game.settings.format(carbyneDrillMeteoriteCost); });
    Game.ui.bindElement('woodburner', function(){ return Game.settings.format(woodburner); });
    Game.ui.bindElement('woodburnerMetalCost', function(){ return Game.settings.format(woodburnerMetalCost); });
    Game.ui.bindElement('woodburnerWoodCost', function(){ return Game.settings.format(woodburnerWoodCost); });
    Game.ui.bindElement('furnace', function(){ return Game.settings.format(furnace); });
    Game.ui.bindElement('furnaceMetalCost', function(){ return Game.settings.format(furnaceMetalCost); });
    Game.ui.bindElement('furnaceWoodCost', function(){ return Game.settings.format(furnaceWoodCost); });
    Game.ui.bindElement('furnaceOilCost', function(){ return Game.settings.format(furnaceOilCost); });
    Game.ui.bindElement('furnaceOutput', function(){ return Game.settings.format(furnaceOutput); });
    Game.ui.bindElement('furnaceWoodInput', function(){ return Game.settings.format(furnaceWoodInput); });
    Game.ui.bindElement('kiln', function(){ return Game.settings.format(kiln); });
    Game.ui.bindElement('kilnLunariteCost', function(){ return Game.settings.format(kilnLunariteCost); });
    Game.ui.bindElement('kilnGemCost', function(){ return Game.settings.format(kilnGemCost); });
    Game.ui.bindElement('kilnSiliconCost', function(){ return Game.settings.format(kilnSiliconCost); });
    Game.ui.bindElement('fryer', function(){ return Game.settings.format(fryer); });
    Game.ui.bindElement('fryerLunariteCost', function(){ return Game.settings.format(fryerLunariteCost); });
    Game.ui.bindElement('fryerLavaCost', function(){ return Game.settings.format(fryerLavaCost); });
    Game.ui.bindElement('fryerMeteoriteCost', function(){ return Game.settings.format(fryerMeteoriteCost); });
    Game.ui.bindElement('woodcutter', function(){ return Game.settings.format(woodcutter); });
    Game.ui.bindElement('woodcutterMetalCost', function(){ return Game.settings.format(woodcutterMetalCost); });
    Game.ui.bindElement('woodcutterWoodCost', function(){ return Game.settings.format(woodcutterWoodCost); });
    Game.ui.bindElement('laserCutter', function(){ return Game.settings.format(laserCutter); });
    Game.ui.bindElement('laserCutterMetalCost', function(){ return Game.settings.format(laserCutterMetalCost); });
    Game.ui.bindElement('laserCutterGemCost', function(){ return Game.settings.format(laserCutterGemCost); });
    Game.ui.bindElement('laserCutterOilCost', function(){ return Game.settings.format(laserCutterOilCost); });
    Game.ui.bindElement('laserCutterOutput', function(){ return Game.settings.format(laserCutterOutput); });
    Game.ui.bindElement('deforester', function(){ return Game.settings.format(deforester); });
    Game.ui.bindElement('deforesterLunariteCost', function(){ return Game.settings.format(deforesterLunariteCost); });
    Game.ui.bindElement('deforesterTitaniumCost', function(){ return Game.settings.format(deforesterTitaniumCost); });
    Game.ui.bindElement('deforesterSiliconCost', function(){ return Game.settings.format(deforesterSiliconCost); });
    Game.ui.bindElement('infuser', function(){ return Game.settings.format(infuser); });
    Game.ui.bindElement('infuserLunariteCost', function(){ return Game.settings.format(infuserLunariteCost); });
    Game.ui.bindElement('infuserOilCost', function(){ return Game.settings.format(infuserOilCost); });
    Game.ui.bindElement('infuserMeteoriteCost', function(){ return Game.settings.format(infuserMeteoriteCost); });
    Game.ui.bindElement('moonWorker', function(){ return Game.settings.format(moonWorker); });
    Game.ui.bindElement('moonWorkerGemCost', function(){ return Game.settings.format(moonWorkerGemCost); });
    Game.ui.bindElement('moonDrill', function(){ return Game.settings.format(moonDrill); });
    Game.ui.bindElement('moonDrillMetalCost', function(){ return Game.settings.format(moonDrillMetalCost); });
    Game.ui.bindElement('moonDrillGemCost', function(){ return Game.settings.format(moonDrillGemCost); });
    Game.ui.bindElement('moonDrillOilCost', function(){ return Game.settings.format(moonDrillOilCost); });
    Game.ui.bindElement('moonQuarry', function(){ return Game.settings.format(moonQuarry); });
    Game.ui.bindElement('moonQuarryLunariteCost', function(){ return Game.settings.format(moonQuarryLunariteCost); });
    Game.ui.bindElement('moonQuarryGemCost', function(){ return Game.settings.format(moonQuarryGemCost); });
    Game.ui.bindElement('moonQuarrySiliconCost', function(){ return Game.settings.format(moonQuarrySiliconCost); });
    Game.ui.bindElement('planetExcavator', function(){ return Game.settings.format(planetExcavator); });
    Game.ui.bindElement('planetExcavatorTitaniumCost', function(){ return Game.settings.format(planetExcavatorTitaniumCost); });
    Game.ui.bindElement('planetExcavatorIceCost', function(){ return Game.settings.format(planetExcavatorIceCost); });
    Game.ui.bindElement('planetExcavatorMeteoriteCost', function(){ return Game.settings.format(planetExcavatorMeteoriteCost); });
    Game.ui.bindElement('vacuum', function(){ return Game.settings.format(vacuum); });
    Game.ui.bindElement('vacuumLunariteCost', function(){ return Game.settings.format(vacuumLunariteCost); });
    Game.ui.bindElement('vacuumGemCost', function(){ return Game.settings.format(vacuumGemCost); });
    Game.ui.bindElement('suctionExcavator', function(){ return Game.settings.format(suctionExcavator); });
    Game.ui.bindElement('suctionExcavatorLunariteCost', function(){ return Game.settings.format(suctionExcavatorLunariteCost); });
    Game.ui.bindElement('suctionExcavatorGemCost', function(){ return Game.settings.format(suctionExcavatorGemCost); });
    Game.ui.bindElement('suctionExcavatorOilCost', function(){ return Game.settings.format(suctionExcavatorOilCost); });
    Game.ui.bindElement('spaceCow', function(){ return Game.settings.format(spaceCow); });
    Game.ui.bindElement('spaceCowTitaniumCost', function(){ return Game.settings.format(spaceCowTitaniumCost); });
    Game.ui.bindElement('spaceCowLunariteCost', function(){ return Game.settings.format(spaceCowLunariteCost); });
    Game.ui.bindElement('spaceCowSiliconCost', function(){ return Game.settings.format(spaceCowSiliconCost); });
    Game.ui.bindElement('vent', function(){ return Game.settings.format(vent); });
    Game.ui.bindElement('ventHeliumCost', function(){ return Game.settings.format(ventHeliumCost); });
    Game.ui.bindElement('ventLunariteCost', function(){ return Game.settings.format(ventLunariteCost); });
    Game.ui.bindElement('ventMeteoriteCost', function(){ return Game.settings.format(ventMeteoriteCost); });
    Game.ui.bindElement('explorer', function(){ return Game.settings.format(explorer); });
    Game.ui.bindElement('explorerGemCost', function(){ return Game.settings.format(explorerGemCost); });
    Game.ui.bindElement('lunariteDrill', function(){ return Game.settings.format(lunariteDrill); });
    Game.ui.bindElement('lunariteDrillLunariteCost', function(){ return Game.settings.format(lunariteDrillLunariteCost); });
    Game.ui.bindElement('lunariteDrillGemCost', function(){ return Game.settings.format(lunariteDrillGemCost); });
    Game.ui.bindElement('lunariteDrillOilCost', function(){ return Game.settings.format(lunariteDrillOilCost); });
    Game.ui.bindElement('pentaDrill', function(){ return Game.settings.format(pentaDrill); });
    Game.ui.bindElement('pentaDrillLunariteCost', function(){ return Game.settings.format(pentaDrillLunariteCost); });
    Game.ui.bindElement('pentaDrillGemCost', function(){ return Game.settings.format(pentaDrillGemCost); });
    Game.ui.bindElement('pentaDrillSiliconCost', function(){ return Game.settings.format(pentaDrillSiliconCost); });
    Game.ui.bindElement('titanDrill', function(){ return Game.settings.format(titanDrill); });
    Game.ui.bindElement('titanDrillLunariteCost', function(){ return Game.settings.format(titanDrillLunariteCost); });
    Game.ui.bindElement('titanDrillGoldCost', function(){ return Game.settings.format(titanDrillGoldCost); });
    Game.ui.bindElement('titanDrillMeteoriteCost', function(){ return Game.settings.format(titanDrillMeteoriteCost); });
    Game.ui.bindElement('droid', function(){ return Game.settings.format(droid); });
    Game.ui.bindElement('droidLunariteCost', function(){ return Game.settings.format(droidLunariteCost); });
    Game.ui.bindElement('droidMethaneCost', function(){ return Game.settings.format(droidMethaneCost); });
    Game.ui.bindElement('destroyer', function(){ return Game.settings.format(destroyer); });
    Game.ui.bindElement('destroyerLunariteCost', function(){ return Game.settings.format(destroyerLunariteCost); });
    Game.ui.bindElement('destroyerGemCost', function(){ return Game.settings.format(destroyerGemCost); });
    Game.ui.bindElement('destroyerOilCost', function(){ return Game.settings.format(destroyerOilCost); });
    Game.ui.bindElement('deathStar', function(){ return Game.settings.format(deathStar); });
    Game.ui.bindElement('deathStarLunariteCost', function(){ return Game.settings.format(deathStarLunariteCost); });
    Game.ui.bindElement('deathStarSilverCost', function(){ return Game.settings.format(deathStarSilverCost); });
    Game.ui.bindElement('deathStarSiliconCost', function(){ return Game.settings.format(deathStarSiliconCost); });
    Game.ui.bindElement('actuator', function(){ return Game.settings.format(actuator); });
    Game.ui.bindElement('actuatorLunariteCost', function(){ return Game.settings.format(actuatorLunariteCost); });
    Game.ui.bindElement('actuatorHeliumCost', function(){ return Game.settings.format(actuatorHeliumCost); });
    Game.ui.bindElement('actuatorMeteoriteCost', function(){ return Game.settings.format(actuatorMeteoriteCost); });
    Game.ui.bindElement('scout', function(){ return Game.settings.format(scout); });
    Game.ui.bindElement('scoutLunariteCost', function(){ return Game.settings.format(scoutLunariteCost); });
    Game.ui.bindElement('scoutTitaniumCost', function(){ return Game.settings.format(scoutTitaniumCost); });
    Game.ui.bindElement('spaceLaser', function(){ return Game.settings.format(spaceLaser); });
    Game.ui.bindElement('spaceLaserLunariteCost', function(){ return Game.settings.format(spaceLaserLunariteCost); });
    Game.ui.bindElement('spaceLaserGemCost', function(){ return Game.settings.format(spaceLaserGemCost); });
    Game.ui.bindElement('spaceLaserOilCost', function(){ return Game.settings.format(spaceLaserOilCost); });
    Game.ui.bindElement('bertha', function(){ return Game.settings.format(bertha); });
    Game.ui.bindElement('berthaTitaniumCost', function(){ return Game.settings.format(berthaTitaniumCost); });
    Game.ui.bindElement('berthaLunariteCost', function(){ return Game.settings.format(berthaLunariteCost); });
    Game.ui.bindElement('berthaSiliconCost', function(){ return Game.settings.format(berthaSiliconCost); });
    Game.ui.bindElement('cannon', function(){ return Game.settings.format(cannon); });
    Game.ui.bindElement('cannonOilCost', function(){ return Game.settings.format(cannonOilCost); });
    Game.ui.bindElement('cannonLunariteCost', function(){ return Game.settings.format(cannonLunariteCost); });
    Game.ui.bindElement('cannonMeteoriteCost', function(){ return Game.settings.format(cannonMeteoriteCost); });
    Game.ui.bindElement('blowtorch', function(){ return Game.settings.format(blowtorch); });
    Game.ui.bindElement('blowtorchLunariteCost', function(){ return Game.settings.format(blowtorchLunariteCost); });
    Game.ui.bindElement('blowtorchTitaniumCost', function(){ return Game.settings.format(blowtorchTitaniumCost); });
    Game.ui.bindElement('scorcher', function(){ return Game.settings.format(scorcher); });
    Game.ui.bindElement('scorcherLunariteCost', function(){ return Game.settings.format(scorcherLunariteCost); });
    Game.ui.bindElement('scorcherGemCost', function(){ return Game.settings.format(scorcherGemCost); });
    Game.ui.bindElement('scorcherOilCost', function(){ return Game.settings.format(scorcherOilCost); });
    Game.ui.bindElement('annihilator', function(){ return Game.settings.format(annihilator); });
    Game.ui.bindElement('annihilatorLunariteCost', function(){ return Game.settings.format(annihilatorLunariteCost); });
    Game.ui.bindElement('annihilatorGemCost', function(){ return Game.settings.format(annihilatorGemCost); });
    Game.ui.bindElement('annihilatorSilverCost', function(){ return Game.settings.format(annihilatorSilverCost); });
    Game.ui.bindElement('desert', function(){ return Game.settings.format(desert); });
    Game.ui.bindElement('desertLunariteCost', function(){ return Game.settings.format(desertLunariteCost); });
    Game.ui.bindElement('desertSiliconCost', function(){ return Game.settings.format(desertSiliconCost); });
    Game.ui.bindElement('desertMeteoriteCost', function(){ return Game.settings.format(desertMeteoriteCost); });
    Game.ui.bindElement('lab', function(){ return Game.settings.format(lab); });
    Game.ui.bindElement('labWoodCost', function(){ return Game.settings.format(labWoodCost); });
    Game.ui.bindElement('labGemCost', function(){ return Game.settings.format(labGemCost); });
    Game.ui.bindElement('labMetalCost', function(){ return Game.settings.format(labMetalCost); });
    Game.ui.bindElement('labT2', function(){ return Game.settings.format(labT2); });
    Game.ui.bindElement('labT2WoodCost', function(){ return Game.settings.format(labT2WoodCost); });
    Game.ui.bindElement('labT2GemCost', function(){ return Game.settings.format(labT2GemCost); });
    Game.ui.bindElement('labT2MetalCost', function(){ return Game.settings.format(labT2MetalCost); });
    Game.ui.bindElement('labT3', function(){ return Game.settings.format(labT3); });
    Game.ui.bindElement('labT3WoodCost', function(){ return Game.settings.format(labT3WoodCost); });
    Game.ui.bindElement('labT3GemCost', function(){ return Game.settings.format(labT3GemCost); });
    Game.ui.bindElement('labT3MetalCost', function(){ return Game.settings.format(labT3MetalCost); });
    Game.ui.bindElement('labT4', function(){ return Game.settings.format(labT4); });
    Game.ui.bindElement('labT4WoodCost', function(){ return Game.settings.format(labT4WoodCost); });
    Game.ui.bindElement('labT4GemCost', function(){ return Game.settings.format(labT4GemCost); });
    Game.ui.bindElement('labT4MetalCost', function(){ return Game.settings.format(labT4MetalCost); });
    Game.ui.bindElement('chemicalPlant', function(){ return Game.settings.format(chemicalPlant); });
    Game.ui.bindElement('chemicalPlantMetalCost', function(){ return Game.settings.format(chemicalPlantMetalCost); });
    Game.ui.bindElement('chemicalPlantGemCost', function(){ return Game.settings.format(chemicalPlantGemCost); });
    Game.ui.bindElement('chemicalPlantOilCost', function(){ return Game.settings.format(chemicalPlantOilCost); });
    Game.ui.bindElement('oxidisation', function(){ return Game.settings.format(oxidisation); });
    Game.ui.bindElement('oxidisationMetalCost', function(){ return Game.settings.format(oxidisationMetalCost); });
    Game.ui.bindElement('oxidisationGemCost', function(){ return Game.settings.format(oxidisationGemCost); });
    Game.ui.bindElement('oxidisationOilCost', function(){ return Game.settings.format(oxidisationOilCost); });
    Game.ui.bindElement('hydrazine', function(){ return Game.settings.format(hydrazine); });
    Game.ui.bindElement('hydrazineTitaniumCost', function(){ return Game.settings.format(hydrazineTitaniumCost); });
    Game.ui.bindElement('hydrazineSiliconCost', function(){ return Game.settings.format(hydrazineSiliconCost); });
    Game.ui.bindElement('hydrazineGoldCost', function(){ return Game.settings.format(hydrazineGoldCost); });
    Game.ui.bindElement('grinder', function(){ return Game.settings.format(grinder); });
    Game.ui.bindElement('grinderTitaniumCost', function(){ return Game.settings.format(grinderTitaniumCost); });
    Game.ui.bindElement('grinderLunariteCost', function(){ return Game.settings.format(grinderLunariteCost); });
    Game.ui.bindElement('grinderGoldCost', function(){ return Game.settings.format(grinderGoldCost); });
    Game.ui.bindElement('cubic', function(){ return Game.settings.format(cubic); });
    Game.ui.bindElement('cubicUraniumCost', function(){ return Game.settings.format(cubicUraniumCost); });
    Game.ui.bindElement('cubicLunariteCost', function(){ return Game.settings.format(cubicLunariteCost); });
    Game.ui.bindElement('cubicOilCost', function(){ return Game.settings.format(cubicOilCost); });
    Game.ui.bindElement('enricher', function(){ return Game.settings.format(enricher); });
    Game.ui.bindElement('enricherTitaniumCost', function(){ return Game.settings.format(enricherTitaniumCost); });
    Game.ui.bindElement('enricherLunariteCost', function(){ return Game.settings.format(enricherLunariteCost); });
    Game.ui.bindElement('enricherSiliconCost', function(){ return Game.settings.format(enricherSiliconCost); });
    Game.ui.bindElement('recycler', function(){ return Game.settings.format(recycler); });
    Game.ui.bindElement('recyclerMethaneCost', function(){ return Game.settings.format(recyclerMethaneCost); });
    Game.ui.bindElement('recyclerLunariteCost', function(){ return Game.settings.format(recyclerLunariteCost); });
    Game.ui.bindElement('recyclerMeteoriteCost', function(){ return Game.settings.format(recyclerMeteoriteCost); });
    Game.ui.bindElement('crucible', function(){ return Game.settings.format(crucible); });
    Game.ui.bindElement('crucibleGemCost', function(){ return Game.settings.format(crucibleGemCost); });
    Game.ui.bindElement('crucibleLunariteCost', function(){ return Game.settings.format(crucibleLunariteCost); });
    Game.ui.bindElement('extractor', function(){ return Game.settings.format(extractor); });
    Game.ui.bindElement('extractorTitaniumCost', function(){ return Game.settings.format(extractorTitaniumCost); });
    Game.ui.bindElement('extractorLunariteCost', function(){ return Game.settings.format(extractorLunariteCost); });
    Game.ui.bindElement('extractorSiliconCost', function(){ return Game.settings.format(extractorSiliconCost); });
    Game.ui.bindElement('extruder', function(){ return Game.settings.format(extruder); });
    Game.ui.bindElement('extruderTitaniumCost', function(){ return Game.settings.format(extruderTitaniumCost); });
    Game.ui.bindElement('extruderLunariteCost', function(){ return Game.settings.format(extruderLunariteCost); });
    Game.ui.bindElement('extruderSiliconCost', function(){ return Game.settings.format(extruderSiliconCost); });
    Game.ui.bindElement('veluptuator', function(){ return Game.settings.format(veluptuator); });
    Game.ui.bindElement('veluptuatorGoldCost', function(){ return Game.settings.format(veluptuatorGoldCost); });
    Game.ui.bindElement('veluptuatorLunariteCost', function(){ return Game.settings.format(veluptuatorLunariteCost); });
    Game.ui.bindElement('veluptuatorMeteoriteCost', function(){ return Game.settings.format(veluptuatorMeteoriteCost); });
    Game.ui.bindElement('collector', function(){ return Game.settings.format(collector); });
    Game.ui.bindElement('collectorLunariteCost', function(){ return Game.settings.format(collectorLunariteCost); });
    Game.ui.bindElement('collectorTitaniumCost', function(){ return Game.settings.format(collectorTitaniumCost); });
    Game.ui.bindElement('magnet', function(){ return Game.settings.format(magnet); });
    Game.ui.bindElement('magnetLunariteCost', function(){ return Game.settings.format(magnetLunariteCost); });
    Game.ui.bindElement('magnetTitaniumCost', function(){ return Game.settings.format(magnetTitaniumCost); });
    Game.ui.bindElement('magnetGoldCost', function(){ return Game.settings.format(magnetGoldCost); });
    Game.ui.bindElement('eCell', function(){ return Game.settings.format(eCell); });
    Game.ui.bindElement('eCellSilverCost', function(){ return Game.settings.format(eCellSilverCost); });
    Game.ui.bindElement('eCellGoldCost', function(){ return Game.settings.format(eCellGoldCost); });
    Game.ui.bindElement('eCellSiliconCost', function(){ return Game.settings.format(eCellSiliconCost); });
    Game.ui.bindElement('hindenburg', function(){ return Game.settings.format(hindenburg); });
    Game.ui.bindElement('hindenburgLunariteCost', function(){ return Game.settings.format(hindenburgLunariteCost); });
    Game.ui.bindElement('hindenburgMethaneCost', function(){ return Game.settings.format(hindenburgMethaneCost); });
    Game.ui.bindElement('hindenburgMeteoriteCost', function(){ return Game.settings.format(hindenburgMeteoriteCost); });
    Game.ui.bindElement('drone', function(){ return Game.settings.format(drone); });
    Game.ui.bindElement('droneLunariteCost', function(){ return Game.settings.format(droneLunariteCost); });
    Game.ui.bindElement('droneSiliconCost', function(){ return Game.settings.format(droneSiliconCost); });
    Game.ui.bindElement('tanker', function(){ return Game.settings.format(tanker); });
    Game.ui.bindElement('tankerLunariteCost', function(){ return Game.settings.format(tankerLunariteCost); });
    Game.ui.bindElement('tankerTitaniumCost', function(){ return Game.settings.format(tankerTitaniumCost); });
    Game.ui.bindElement('tankerSiliconCost', function(){ return Game.settings.format(tankerSiliconCost); });
    Game.ui.bindElement('compressor', function(){ return Game.settings.format(compressor); });
    Game.ui.bindElement('compressorLunariteCost', function(){ return Game.settings.format(compressorLunariteCost); });
    Game.ui.bindElement('compressorTitaniumCost', function(){ return Game.settings.format(compressorTitaniumCost); });
    Game.ui.bindElement('compressorSiliconCost', function(){ return Game.settings.format(compressorSiliconCost); });
    Game.ui.bindElement('skimmer', function(){ return Game.settings.format(skimmer); });
    Game.ui.bindElement('skimmerLunariteCost', function(){ return Game.settings.format(skimmerLunariteCost); });
    Game.ui.bindElement('skimmerTitaniumCost', function(){ return Game.settings.format(skimmerTitaniumCost); });
    Game.ui.bindElement('skimmerMeteoriteCost', function(){ return Game.settings.format(skimmerMeteoriteCost); });
    Game.ui.bindElement('icePick', function(){ return Game.settings.format(icePick); });
    Game.ui.bindElement('icePickLunariteCost', function(){ return Game.settings.format(icePickLunariteCost); });
    Game.ui.bindElement('icePickGemCost', function(){ return Game.settings.format(icePickGemCost); });
    Game.ui.bindElement('iceDrill', function(){ return Game.settings.format(iceDrill); });
    Game.ui.bindElement('iceDrillLunariteCost', function(){ return Game.settings.format(iceDrillLunariteCost); });
    Game.ui.bindElement('iceDrillTitaniumCost', function(){ return Game.settings.format(iceDrillTitaniumCost); });
    Game.ui.bindElement('iceDrillSiliconCost', function(){ return Game.settings.format(iceDrillSiliconCost); });
    Game.ui.bindElement('freezer', function(){ return Game.settings.format(freezer); });
    Game.ui.bindElement('freezerLunariteCost', function(){ return Game.settings.format(freezerLunariteCost); });
    Game.ui.bindElement('freezerTitaniumCost', function(){ return Game.settings.format(freezerTitaniumCost); });
    Game.ui.bindElement('freezerSiliconCost', function(){ return Game.settings.format(freezerSiliconCost); });
    Game.ui.bindElement('mrFreeze', function(){ return Game.settings.format(mrFreeze); });
    Game.ui.bindElement('mrFreezeWoodCost', function(){ return Game.settings.format(mrFreezeWoodCost); });
    Game.ui.bindElement('mrFreezeHeliumCost', function(){ return Game.settings.format(mrFreezeHeliumCost); });
    Game.ui.bindElement('mrFreezeMeteoriteCost', function(){ return Game.settings.format(mrFreezeMeteoriteCost); });
    Game.ui.bindElement('printer', function(){ return Game.settings.format(printer); });
    Game.ui.bindElement('printerLunariteCost', function(){ return Game.settings.format(printerLunariteCost); });
    Game.ui.bindElement('printerSiliconCost', function(){ return Game.settings.format(printerSiliconCost); });
    Game.ui.bindElement('web', function(){ return Game.settings.format(web); });
    Game.ui.bindElement('webLunariteCost', function(){ return Game.settings.format(webLunariteCost); });
    Game.ui.bindElement('webUraniumCost', function(){ return Game.settings.format(webUraniumCost); });
    Game.ui.bindElement('webSiliconCost', function(){ return Game.settings.format(webSiliconCost); });
    Game.ui.bindElement('dyson', function(){ return Game.settings.format(dyson); });
    Game.ui.bindElement('dysonPieces', function(){ return Game.settings.format(dyson); });
    Game.ui.bindElement('dysonPieces2', function(){ return Game.settings.format(dyson); });
    Game.ui.bindElement('dysonPieces3', function(){ return Game.settings.format(dyson); });
    Game.ui.bindElement('dysonTitaniumCost', function(){ return Game.settings.format(dysonTitaniumCost); });
    Game.ui.bindElement('dysonGoldCost', function(){ return Game.settings.format(dysonGoldCost); });
    Game.ui.bindElement('dysonSiliconCost', function(){ return Game.settings.format(dysonSiliconCost); });
    Game.ui.bindElement('dysonMeteoriteCost', function(){ return Game.settings.format(dysonMeteoriteCost); });
    Game.ui.bindElement('dysonIceCost', function(){ return Game.settings.format(dysonIceCost); });
    Game.ui.bindElement('ring', function(){ return Game.settings.format(ring); });
    Game.ui.bindElement('swarm', function(){ return Game.settings.format(swarm); });
    Game.ui.bindElement('sphere', function(){ return Game.settings.format(sphere); });

    Game.ui.bindElement('science', function(){
        if(science < 100){
            return Game.settings.format(science, 1);
        }
        else{
            return Game.settings.format(science);
        }
    });

    Game.ui.bindElement('rocketFuel', function(){
        if(rocketFuel < 100) {
            return Game.settings.format(rocketFuel, 1);
        } else {
            return Game.settings.format(rocketFuel);
        }
    });

    Game.ui.bindElement('antimatter', function(){
        if(antimatter < 100) {
            return Game.settings.format(antimatter, 1);
        } else {
            return Game.settings.format(antimatter);
        }
    });
}

function legacyRefreshUI() {
    if(energyLow) {
        $('#energyLow').removeClass('hidden');
    } else {
        $('#energyLow').addClass('hidden');
    }

    if(sphere > 0) {
        $('#buildSphereInfo').hide();
        $('#buildSphereButton').hide();
    }

    $('#heaterToggled').text(heaterToggled === true ? "Off" : "On");
    $('#plasmaticToggled').text(plasmaticToggled === true ? "Off" : "On");
    $('#charcoalToggled').text(charcoalToggled === true ? "Off" : "On");
    $('#rocketFuelToggled').text(rocketFuelToggled === true ? "Off" : "On");
    $('#meteoriteToggled').text(meteoriteToggled === true ? "Off" : "On");
    $('#antimatterToggled').text(antimatterToggled === true ? "Off" : "On");
}
